name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # Déclenche le déploiement lors d'un push sur main

# Donne les permissions nécessaires pour écrire sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # C'est le dossier généré par Vite qui contient le site prêt à l'emploi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
